#!/bin/sh

sessiontype=`loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'`

if [ "$sessiontype" = 'wayland' ]; then
	echo "Currently not supported in $sessiontype"
	exit 1;
fi

terminator -e '
containers=`sudo docker ps --format "{{.Names}}" || pkexec docker ps --format "{{.Names}}"`

if  [ `echo $containers | wc -w` -gt 1 ]; then
    container=`echo $containers | tr "[:blank:]" "\n" | dmenu`
else
    container=$containers
fi

ip=`sudo docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" $container || pkexec docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" $container`
echo $ip
notify-send "Copied ip address of $container to clipboard" "$ip"
echo -n $ip | xclip -selection clipboard
'

