#!/usr/bin/sh

chosen=$(rofi -show file-browser-extended -file-browser-dir ~/Pictures/emojis -file-browser-cmd basename -file-browser-hide-parent -show-icons -theme iggy -no-disable-history)

[ -z "$chosen" ] && exit
#xclip -selection clipboard -t image/png -i "$chosen"
echo $chosen
printf "https://gitlab.com/thecashewtrader/emojis/-/raw/main/$chosen" | xclip -sel c

